add FLAG_IMMUTABLE at TaskScheduler.java
FATAL EXCEPTION: main
                                                                                             Process: kr.apptimer, PID: 5975
                                                                                             java.lang.IllegalArgumentException: kr.apptimer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                             Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.