Fixed problem "edittext doesn't show soft keyboard" Modified layout "edittext text color white->black, gravity->center"
and Exception when tested with "day = 1, hour = 2, minute = 3"

FATAL EXCEPTION: main
                                                                                             Process: kr.apptimer, PID: 31333
                                                                                             java.lang.IllegalArgumentException: kr.apptimer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                             Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                             	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
                                                                                             	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
                                                                                             	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
                                                                                             	at kr.apptimer.dagger.android.TaskScheduler.scheduleTask(TaskScheduler.java:104)
                                                                                             	at kr.apptimer.android.service.AppExpirationOverlayService.lambda$onCreate$1$kr-apptimer-android-service-AppExpirationOverlayService(AppExpirationOverlayService.java:142)
                                                                                             	at kr.apptimer.android.service.AppExpirationOverlayService$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
                                                                                             	at android.view.View.performClick(View.java:7792)
                                                                                             	at android.widget.TextView.performClick(TextView.java:16112)
                                                                                             	at android.view.View.performClickInternal(View.java:7769)
                                                                                             	at android.view.View.access$3800(View.java:910)
                                                                                             	at android.view.View$PerformClick.run(View.java:30218)
                                                                                             	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                             	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                             	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                             	at android.os.Looper.loop(Looper.java:313)
                                                                                             	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)